In [2]:
import numpy as np
import pandas as pd
import sklearn as sk

In [3]:
data=[[40920,8.326976,0.953952,3],[14488,7.153469,1.673904,2],[26052,1.441871,0.805124,1],[75136,13.147394,0.428964,1],[38344,1.669788,0.134296,1]]
dating_df=pd.DataFrame(data,columns=['milage','Liters','Consumtime','target'])
dating_df

milage     Liters  Consumtime  target
0   40920   8.326976    0.953952       3
1   14488   7.153469    1.673904       2
2   26052   1.441871    0.805124       1
3   75136  13.147394    0.428964       1
4   38344   1.669788    0.134296       1

In [13]:
from sklearn.preprocessing import minmax_scale
def minmax_demo(data):
  print(data)
  data_scaled=minmax_scale(data[['milage','Liters','Consumtime']],feature_range=(2,3))
  print('归一化处理结果：\n',data_scaled)
  return None

In [14]:
minmax_demo(dating_df)

   milage     Liters  Consumtime  target
0   40920   8.326976    0.953952       3
1   14488   7.153469    1.673904       2
2   26052   1.441871    0.805124       1
3   75136  13.147394    0.428964       1
4   38344   1.669788    0.134296       1
归一化处理结果：
 [[2.43582641 2.58819286 2.53237967]
 [2.         2.48794044 3.        ]
 [2.19067405 2.         2.43571351]
 [3.         3.         2.19139157]
 [2.3933518  2.01947089 2.        ]]


In [20]:
from sklearn.preprocessing import StandardScaler
def standardise_demo(data):
  print(data)
  scaler=StandardScaler()
  data_scaled=scaler.fit_transform(data[['milage','Liters','Consumtime']])
  print('标准化处理结果：\n',data_scaled)
  return None
standardise_demo(dating_df)

   milage     Liters  Consumtime  target
0   40920   8.326976    0.953952       3
1   14488   7.153469    1.673904       2
2   26052   1.441871    0.805124       1
3   75136  13.147394    0.428964       1
4   38344   1.669788    0.134296       1
标准化处理结果：
 [[ 0.0947602   0.44990013  0.29573441]
 [-1.20166916  0.18312874  1.67200507]
 [-0.63448132 -1.11527928  0.01123265]
 [ 1.77297701  1.54571769 -0.70784025]
 [-0.03158673 -1.06346729 -1.27113187]]
