# 正规方程

In [2]:
#获取数据
import numpy as np
import pandas as pd
import sklearn as sk

data_url = "http://lib.stat.cmu.edu/datasets/boston"
raw_df = pd.read_csv(data_url, sep="\s+", skiprows=22, header=None)
data = np.hstack([raw_df.values[::2, :], raw_df.values[1::2, :2]])
target = raw_df.values[1::2, 2]

In [3]:
raw_df

0      1      2    3      4   ...    6       7    8      9     10
0       0.00632  18.00   2.31  0.0  0.538  ...  65.2  4.0900  1.0  296.0  15.3
1     396.90000   4.98  24.00  NaN    NaN  ...   NaN     NaN  NaN    NaN   NaN
2       0.02731   0.00   7.07  0.0  0.469  ...  78.9  4.9671  2.0  242.0  17.8
3     396.90000   9.14  21.60  NaN    NaN  ...   NaN     NaN  NaN    NaN   NaN
4       0.02729   0.00   7.07  0.0  0.469  ...  61.1  4.9671  2.0  242.0  17.8
...         ...    ...    ...  ...    ...  ...   ...     ...  ...    ...   ...
1007  396.90000   5.64  23.90  NaN    NaN  ...   NaN     NaN  NaN    NaN   NaN
1008    0.10959   0.00  11.93  0.0  0.573  ...  89.3  2.3889  1.0  273.0  21.0
1009  393.45000   6.48  22.00  NaN    NaN  ...   NaN     NaN  NaN    NaN   NaN
1010    0.04741   0.00  11.93  0.0  0.573  ...  80.8  2.5050  1.0  273.0  21.0
1011  396.90000   7.88  11.90  NaN    NaN  ...   NaN     NaN  NaN    NaN   NaN

[1012 rows x 11 columns]

In [4]:
data

array([[6.3200e-03, 1.8000e+01, 2.3100e+00, ..., 1.5300e+01, 3.9690e+02,
        4.9800e+00],
       [2.7310e-02, 0.0000e+00, 7.0700e+00, ..., 1.7800e+01, 3.9690e+02,
        9.1400e+00],
       [2.7290e-02, 0.0000e+00, 7.0700e+00, ..., 1.7800e+01, 3.9283e+02,
        4.0300e+00],
       ...,
       [6.0760e-02, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9690e+02,
        5.6400e+00],
       [1.0959e-01, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9345e+02,
        6.4800e+00],
       [4.7410e-02, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9690e+02,
        7.8800e+00]])

In [5]:
#分割数据
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(data,target)

In [6]:
x_train

array([[  0.57529,   0.     ,   6.2    , ...,  17.4    , 385.91   ,
          2.47   ],
       [  8.24809,   0.     ,  18.1    , ...,  20.2    , 375.87   ,
         16.74   ],
       [  2.44668,   0.     ,  19.58   , ...,  14.7    ,  88.63   ,
         16.14   ],
       ...,
       [ 10.6718 ,   0.     ,  18.1    , ...,  20.2    ,  43.06   ,
         23.98   ],
       [ 14.0507 ,   0.     ,  18.1    , ...,  20.2    ,  35.05   ,
         21.22   ],
       [  1.46336,   0.     ,  19.58   , ...,  14.7    , 374.43   ,
          1.73   ]])

In [7]:
x_test

array([[3.58090e-01, 0.00000e+00, 6.20000e+00, ..., 1.74000e+01,
        3.91700e+02, 9.71000e+00],
       [1.30580e-01, 0.00000e+00, 1.00100e+01, ..., 1.78000e+01,
        3.38630e+02, 1.53700e+01],
       [7.35341e+01, 0.00000e+00, 1.81000e+01, ..., 2.02000e+01,
        1.64500e+01, 2.06200e+01],
       ...,
       [8.79212e+00, 0.00000e+00, 1.81000e+01, ..., 2.02000e+01,
        3.65000e+00, 1.71600e+01],
       [1.78667e+01, 0.00000e+00, 1.81000e+01, ..., 2.02000e+01,
        3.93740e+02, 2.17800e+01],
       [2.39120e-01, 0.00000e+00, 9.69000e+00, ..., 1.92000e+01,
        3.96900e+02, 1.29200e+01]])

In [8]:
y_train

array([41.7, 17.8, 13.1, 22.6, 13.4, 24.8,  8.8, 20.1, 19.6, 21.4, 14.3,
        7.4, 19.3, 21. , 34.9, 32.4, 19.5, 13.1, 33.4, 12.1, 23.4, 21.7,
       43.1, 28.4, 29.6, 35.4, 14.9, 19.4, 22. , 23.3, 18.7, 20.9, 42.3,
       21.7, 20.6, 20.4, 20.2, 26.6, 13.5, 30.1, 19.5, 19.9, 22.2, 37.9,
       29.4, 10.2, 25. , 24.6, 36.2, 22.2, 24. ,  7.2, 25. , 24.7, 30.7,
       19.4, 23.3, 31.7, 16.1, 33.2, 20.2, 27.1, 33. , 22.5, 25. , 33.2,
       36.5, 14.5, 32.5, 20.4, 18.3, 24.6,  8.1, 34.9, 23.1, 27.5, 23.5,
       18.5, 27.9, 15.3, 26.6, 22.6, 30.5, 28. , 15.2, 39.8, 50. , 13.4,
       24.8, 44.8, 19.8, 23. , 17.4, 20. , 24.1, 15.4,  7. , 13.8, 22. ,
       12.6, 38.7, 46.7, 16.2, 24.3, 21.2, 23.1, 13.8, 16.8, 25. , 20.8,
       11.9, 15.7, 20.6, 11.5, 19.3, 22. , 23.2,  9.6, 15. , 17. , 50. ,
       50. , 19.9, 13.3, 17.5, 34.7, 23.9, 21.5, 19.7, 43.8, 18.8,  5. ,
       20.7, 16.2, 12.7, 22.5, 21.9, 19. , 10.2, 14.9, 22. , 20.3, 17.8,
       23.7, 29. , 16.3, 24.5, 13.5, 14.1, 22.6, 14

In [9]:
#标准化
from sklearn.preprocessing import StandardScaler
transfer=StandardScaler()
x_train=transfer.fit_transform(x_train)
x_test=transfer.transform(x_test)

In [10]:
x_train

array([[-0.38371285, -0.48426616, -0.69974668, ..., -0.5006277 ,
         0.32188969, -1.39457682],
       [ 0.69818901, -0.48426616,  1.04435111, ...,  0.828202  ,
         0.20960027,  0.58427429],
       [-0.11983783, -0.48426616,  1.26126411, ..., -1.78199919,
        -3.00295089,  0.50107102],
       ...,
       [ 1.03994383, -0.48426616,  1.04435111, ...,  0.828202  ,
        -3.51261514,  1.58826042],
       [ 1.51638505, -0.48426616,  1.04435111, ...,  0.828202  ,
        -3.60220062,  1.20552538],
       [-0.2584907 , -0.48426616,  1.26126411, ..., -1.78199919,
         0.19349502, -1.49719418]])

In [11]:
#训练模型
from sklearn.linear_model import LinearRegression
estimator=LinearRegression()
estimator.fit(x_train,y_train)

LinearRegression()

In [12]:
#模型评估
from sklearn.metrics import mean_squared_error
y_pred=estimator.predict(x_test)
print("MSE:",mean_squared_error(y_test,y_pred))

MSE: 20.594343920124118


In [13]:
estimator.intercept_

np.float64(22.774670184696607)

In [14]:
estimator.coef_

array([-0.79031369,  0.85875186,  0.37518715,  0.62109211, -2.28988224,
        3.17854903,  0.15252812, -2.91634086,  2.82711336, -2.19201026,
       -2.00154904,  1.03993666, -3.67022311])

In [15]:
y_pred

array([33.38804145, 20.02884792,  5.29514274,  9.25678889, 30.90573963,
       19.0840321 , 16.29113001, 21.36872551, 14.05183106, 21.9510326 ,
       31.75755704, 13.90017642, 19.39676296, 17.75327619, 27.01990534,
       32.30662706, 19.80943512, 22.70411893,  7.63657066, 25.03985253,
       25.15885048, 29.79210213, 27.28630628, 33.08171728, 33.25745907,
       16.77284364, 23.75219435, 20.78631546, 25.4149097 , 22.91263701,
       23.69922014, 15.50290624, 32.68113035, 22.69226603,  0.5457029 ,
       28.11887049, 24.64419513, 27.0188125 , 23.36871666, 17.29205626,
       19.38206848, 29.82825348, 25.95222392, 12.49846071, 14.90250255,
       39.58016524, 20.71705182,  7.839644  , 22.95207761, 29.15683468,
       12.44475619, 23.60197426, 24.19416465, 16.43923484, 20.28070789,
       16.13243413, 30.20959937, 12.84385859, 25.48874664, 28.95731865,
       23.11587772, 20.11768421, 27.98605519, 16.38300115, 19.41935537,
       42.27764842, 19.22145019, 21.10756456, 20.23728248, 17.40

# 梯度下降法

In [ ]:
#获取数据
import numpy as np
import pandas as pd
import sklearn as sk

data_url = "http://lib.stat.cmu.edu/datasets/boston"
raw_df = pd.read_csv(data_url, sep="\s+", skiprows=22, header=None)
data = np.hstack([raw_df.values[::2, :], raw_df.values[1::2, :2]])
target = raw_df.values[1::2, 2]

In [ ]:
raw_df

0      1      2    3      4   ...    6       7    8      9     10
0       0.00632  18.00   2.31  0.0  0.538  ...  65.2  4.0900  1.0  296.0  15.3
1     396.90000   4.98  24.00  NaN    NaN  ...   NaN     NaN  NaN    NaN   NaN
2       0.02731   0.00   7.07  0.0  0.469  ...  78.9  4.9671  2.0  242.0  17.8
3     396.90000   9.14  21.60  NaN    NaN  ...   NaN     NaN  NaN    NaN   NaN
4       0.02729   0.00   7.07  0.0  0.469  ...  61.1  4.9671  2.0  242.0  17.8
...         ...    ...    ...  ...    ...  ...   ...     ...  ...    ...   ...
1007  396.90000   5.64  23.90  NaN    NaN  ...   NaN     NaN  NaN    NaN   NaN
1008    0.10959   0.00  11.93  0.0  0.573  ...  89.3  2.3889  1.0  273.0  21.0
1009  393.45000   6.48  22.00  NaN    NaN  ...   NaN     NaN  NaN    NaN   NaN
1010    0.04741   0.00  11.93  0.0  0.573  ...  80.8  2.5050  1.0  273.0  21.0
1011  396.90000   7.88  11.90  NaN    NaN  ...   NaN     NaN  NaN    NaN   NaN

[1012 rows x 11 columns]

In [ ]:
data

array([[6.3200e-03, 1.8000e+01, 2.3100e+00, ..., 1.5300e+01, 3.9690e+02,
        4.9800e+00],
       [2.7310e-02, 0.0000e+00, 7.0700e+00, ..., 1.7800e+01, 3.9690e+02,
        9.1400e+00],
       [2.7290e-02, 0.0000e+00, 7.0700e+00, ..., 1.7800e+01, 3.9283e+02,
        4.0300e+00],
       ...,
       [6.0760e-02, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9690e+02,
        5.6400e+00],
       [1.0959e-01, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9345e+02,
        6.4800e+00],
       [4.7410e-02, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9690e+02,
        7.8800e+00]])

In [ ]:
#分割数据
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(data,target)

In [ ]:
x_train

array([[  0.57529,   0.     ,   6.2    , ...,  17.4    , 385.91   ,
          2.47   ],
       [  8.24809,   0.     ,  18.1    , ...,  20.2    , 375.87   ,
         16.74   ],
       [  2.44668,   0.     ,  19.58   , ...,  14.7    ,  88.63   ,
         16.14   ],
       ...,
       [ 10.6718 ,   0.     ,  18.1    , ...,  20.2    ,  43.06   ,
         23.98   ],
       [ 14.0507 ,   0.     ,  18.1    , ...,  20.2    ,  35.05   ,
         21.22   ],
       [  1.46336,   0.     ,  19.58   , ...,  14.7    , 374.43   ,
          1.73   ]])

In [ ]:
x_test

array([[3.58090e-01, 0.00000e+00, 6.20000e+00, ..., 1.74000e+01,
        3.91700e+02, 9.71000e+00],
       [1.30580e-01, 0.00000e+00, 1.00100e+01, ..., 1.78000e+01,
        3.38630e+02, 1.53700e+01],
       [7.35341e+01, 0.00000e+00, 1.81000e+01, ..., 2.02000e+01,
        1.64500e+01, 2.06200e+01],
       ...,
       [8.79212e+00, 0.00000e+00, 1.81000e+01, ..., 2.02000e+01,
        3.65000e+00, 1.71600e+01],
       [1.78667e+01, 0.00000e+00, 1.81000e+01, ..., 2.02000e+01,
        3.93740e+02, 2.17800e+01],
       [2.39120e-01, 0.00000e+00, 9.69000e+00, ..., 1.92000e+01,
        3.96900e+02, 1.29200e+01]])

In [ ]:
y_train

array([41.7, 17.8, 13.1, 22.6, 13.4, 24.8,  8.8, 20.1, 19.6, 21.4, 14.3,
        7.4, 19.3, 21. , 34.9, 32.4, 19.5, 13.1, 33.4, 12.1, 23.4, 21.7,
       43.1, 28.4, 29.6, 35.4, 14.9, 19.4, 22. , 23.3, 18.7, 20.9, 42.3,
       21.7, 20.6, 20.4, 20.2, 26.6, 13.5, 30.1, 19.5, 19.9, 22.2, 37.9,
       29.4, 10.2, 25. , 24.6, 36.2, 22.2, 24. ,  7.2, 25. , 24.7, 30.7,
       19.4, 23.3, 31.7, 16.1, 33.2, 20.2, 27.1, 33. , 22.5, 25. , 33.2,
       36.5, 14.5, 32.5, 20.4, 18.3, 24.6,  8.1, 34.9, 23.1, 27.5, 23.5,
       18.5, 27.9, 15.3, 26.6, 22.6, 30.5, 28. , 15.2, 39.8, 50. , 13.4,
       24.8, 44.8, 19.8, 23. , 17.4, 20. , 24.1, 15.4,  7. , 13.8, 22. ,
       12.6, 38.7, 46.7, 16.2, 24.3, 21.2, 23.1, 13.8, 16.8, 25. , 20.8,
       11.9, 15.7, 20.6, 11.5, 19.3, 22. , 23.2,  9.6, 15. , 17. , 50. ,
       50. , 19.9, 13.3, 17.5, 34.7, 23.9, 21.5, 19.7, 43.8, 18.8,  5. ,
       20.7, 16.2, 12.7, 22.5, 21.9, 19. , 10.2, 14.9, 22. , 20.3, 17.8,
       23.7, 29. , 16.3, 24.5, 13.5, 14.1, 22.6, 14

In [ ]:
#标准化
from sklearn.preprocessing import StandardScaler
transfer=StandardScaler()
x_train=transfer.fit_transform(x_train)
x_test=transfer.transform(x_test)

In [ ]:
x_train

array([[-0.38371285, -0.48426616, -0.69974668, ..., -0.5006277 ,
         0.32188969, -1.39457682],
       [ 0.69818901, -0.48426616,  1.04435111, ...,  0.828202  ,
         0.20960027,  0.58427429],
       [-0.11983783, -0.48426616,  1.26126411, ..., -1.78199919,
        -3.00295089,  0.50107102],
       ...,
       [ 1.03994383, -0.48426616,  1.04435111, ...,  0.828202  ,
        -3.51261514,  1.58826042],
       [ 1.51638505, -0.48426616,  1.04435111, ...,  0.828202  ,
        -3.60220062,  1.20552538],
       [-0.2584907 , -0.48426616,  1.26126411, ..., -1.78199919,
         0.19349502, -1.49719418]])

In [26]:
#训练模型
from sklearn.linear_model import SGDRegressor
estimator=SGDRegressor(max_iter=1000)
estimator.fit(x_train,y_train)

SGDRegressor()

In [27]:
#模型评估
from sklearn.metrics import mean_squared_error
y_pred=estimator.predict(x_test)
print("MSE:",mean_squared_error(y_test,y_pred))

MSE: 20.384534023248012


In [23]:
estimator.intercept_

array([-391.95797255])

In [24]:
estimator.coef_

array([ 1.95479899e+03,  1.24812296e+02, -3.05111692e+02, -7.01192625e+02,
        4.99464443e+02, -7.62551801e+02, -3.76672087e+02,  4.35738454e+02,
       -8.37249018e+02,  5.39044400e+02, -9.42438614e-01,  8.23127043e+02,
       -1.32443091e+03])

In [25]:
y_pred

array([-4.09310207e+03, -1.24789891e+03,  1.36780268e+04, -2.84396875e+03,
        1.24153281e+03,  4.91179282e+02, -4.80312422e+03, -2.98151972e+03,
       -1.17809867e+03,  8.76253743e+02, -4.46959177e+02, -3.92333075e+03,
        6.54078856e+01, -1.35074242e+03,  1.17472599e+03, -2.65271114e+03,
       -6.94716702e+02, -1.48710235e+03, -1.26962892e+03,  9.63837186e+01,
        4.20675550e+02,  2.36338568e+03,  1.01500889e+03,  7.54552987e+02,
        6.12663329e+02, -1.95075638e+03, -4.50342816e+02, -2.52439556e+01,
        1.15861466e+01, -1.99577985e+03,  7.72822499e+01, -5.17337621e+02,
       -2.21468745e+03,  5.59104144e+02, -2.79338901e+03, -4.29322654e+02,
        1.56822058e+02,  4.62680801e+02, -3.99169891e+02,  8.79357496e+02,
       -2.65223258e+03,  1.29665848e+03, -2.97044309e+02,  3.11766472e+03,
        2.09713217e+04,  2.78627740e+02, -1.21634920e+03, -1.09107846e+03,
       -1.23901173e+03,  5.48423516e+01, -1.52467665e+03, -8.40667613e+01,
        5.27338190e+02, -

# 岭回归

In [ ]:
#获取数据
import numpy as np
import pandas as pd
import sklearn as sk

data_url = "http://lib.stat.cmu.edu/datasets/boston"
raw_df = pd.read_csv(data_url, sep="\s+", skiprows=22, header=None)
data = np.hstack([raw_df.values[::2, :], raw_df.values[1::2, :2]])
target = raw_df.values[1::2, 2]

In [ ]:
raw_df

0      1      2    3      4   ...    6       7    8      9     10
0       0.00632  18.00   2.31  0.0  0.538  ...  65.2  4.0900  1.0  296.0  15.3
1     396.90000   4.98  24.00  NaN    NaN  ...   NaN     NaN  NaN    NaN   NaN
2       0.02731   0.00   7.07  0.0  0.469  ...  78.9  4.9671  2.0  242.0  17.8
3     396.90000   9.14  21.60  NaN    NaN  ...   NaN     NaN  NaN    NaN   NaN
4       0.02729   0.00   7.07  0.0  0.469  ...  61.1  4.9671  2.0  242.0  17.8
...         ...    ...    ...  ...    ...  ...   ...     ...  ...    ...   ...
1007  396.90000   5.64  23.90  NaN    NaN  ...   NaN     NaN  NaN    NaN   NaN
1008    0.10959   0.00  11.93  0.0  0.573  ...  89.3  2.3889  1.0  273.0  21.0
1009  393.45000   6.48  22.00  NaN    NaN  ...   NaN     NaN  NaN    NaN   NaN
1010    0.04741   0.00  11.93  0.0  0.573  ...  80.8  2.5050  1.0  273.0  21.0
1011  396.90000   7.88  11.90  NaN    NaN  ...   NaN     NaN  NaN    NaN   NaN

[1012 rows x 11 columns]

In [ ]:
data

array([[6.3200e-03, 1.8000e+01, 2.3100e+00, ..., 1.5300e+01, 3.9690e+02,
        4.9800e+00],
       [2.7310e-02, 0.0000e+00, 7.0700e+00, ..., 1.7800e+01, 3.9690e+02,
        9.1400e+00],
       [2.7290e-02, 0.0000e+00, 7.0700e+00, ..., 1.7800e+01, 3.9283e+02,
        4.0300e+00],
       ...,
       [6.0760e-02, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9690e+02,
        5.6400e+00],
       [1.0959e-01, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9345e+02,
        6.4800e+00],
       [4.7410e-02, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9690e+02,
        7.8800e+00]])

In [ ]:
#分割数据
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(data,target)

In [ ]:
x_train

array([[  0.57529,   0.     ,   6.2    , ...,  17.4    , 385.91   ,
          2.47   ],
       [  8.24809,   0.     ,  18.1    , ...,  20.2    , 375.87   ,
         16.74   ],
       [  2.44668,   0.     ,  19.58   , ...,  14.7    ,  88.63   ,
         16.14   ],
       ...,
       [ 10.6718 ,   0.     ,  18.1    , ...,  20.2    ,  43.06   ,
         23.98   ],
       [ 14.0507 ,   0.     ,  18.1    , ...,  20.2    ,  35.05   ,
         21.22   ],
       [  1.46336,   0.     ,  19.58   , ...,  14.7    , 374.43   ,
          1.73   ]])

In [ ]:
x_test

array([[3.58090e-01, 0.00000e+00, 6.20000e+00, ..., 1.74000e+01,
        3.91700e+02, 9.71000e+00],
       [1.30580e-01, 0.00000e+00, 1.00100e+01, ..., 1.78000e+01,
        3.38630e+02, 1.53700e+01],
       [7.35341e+01, 0.00000e+00, 1.81000e+01, ..., 2.02000e+01,
        1.64500e+01, 2.06200e+01],
       ...,
       [8.79212e+00, 0.00000e+00, 1.81000e+01, ..., 2.02000e+01,
        3.65000e+00, 1.71600e+01],
       [1.78667e+01, 0.00000e+00, 1.81000e+01, ..., 2.02000e+01,
        3.93740e+02, 2.17800e+01],
       [2.39120e-01, 0.00000e+00, 9.69000e+00, ..., 1.92000e+01,
        3.96900e+02, 1.29200e+01]])

In [ ]:
y_train

array([41.7, 17.8, 13.1, 22.6, 13.4, 24.8,  8.8, 20.1, 19.6, 21.4, 14.3,
        7.4, 19.3, 21. , 34.9, 32.4, 19.5, 13.1, 33.4, 12.1, 23.4, 21.7,
       43.1, 28.4, 29.6, 35.4, 14.9, 19.4, 22. , 23.3, 18.7, 20.9, 42.3,
       21.7, 20.6, 20.4, 20.2, 26.6, 13.5, 30.1, 19.5, 19.9, 22.2, 37.9,
       29.4, 10.2, 25. , 24.6, 36.2, 22.2, 24. ,  7.2, 25. , 24.7, 30.7,
       19.4, 23.3, 31.7, 16.1, 33.2, 20.2, 27.1, 33. , 22.5, 25. , 33.2,
       36.5, 14.5, 32.5, 20.4, 18.3, 24.6,  8.1, 34.9, 23.1, 27.5, 23.5,
       18.5, 27.9, 15.3, 26.6, 22.6, 30.5, 28. , 15.2, 39.8, 50. , 13.4,
       24.8, 44.8, 19.8, 23. , 17.4, 20. , 24.1, 15.4,  7. , 13.8, 22. ,
       12.6, 38.7, 46.7, 16.2, 24.3, 21.2, 23.1, 13.8, 16.8, 25. , 20.8,
       11.9, 15.7, 20.6, 11.5, 19.3, 22. , 23.2,  9.6, 15. , 17. , 50. ,
       50. , 19.9, 13.3, 17.5, 34.7, 23.9, 21.5, 19.7, 43.8, 18.8,  5. ,
       20.7, 16.2, 12.7, 22.5, 21.9, 19. , 10.2, 14.9, 22. , 20.3, 17.8,
       23.7, 29. , 16.3, 24.5, 13.5, 14.1, 22.6, 14

In [ ]:
#标准化
from sklearn.preprocessing import StandardScaler
transfer=StandardScaler()
x_train=transfer.fit_transform(x_train)
x_test=transfer.transform(x_test)

In [ ]:
x_train

array([[-0.38371285, -0.48426616, -0.69974668, ..., -0.5006277 ,
         0.32188969, -1.39457682],
       [ 0.69818901, -0.48426616,  1.04435111, ...,  0.828202  ,
         0.20960027,  0.58427429],
       [-0.11983783, -0.48426616,  1.26126411, ..., -1.78199919,
        -3.00295089,  0.50107102],
       ...,
       [ 1.03994383, -0.48426616,  1.04435111, ...,  0.828202  ,
        -3.51261514,  1.58826042],
       [ 1.51638505, -0.48426616,  1.04435111, ...,  0.828202  ,
        -3.60220062,  1.20552538],
       [-0.2584907 , -0.48426616,  1.26126411, ..., -1.78199919,
         0.19349502, -1.49719418]])

In [28]:
#训练模型
from sklearn.linear_model import Ridge
estimator=Ridge(alpha=1)
estimator.fit(x_train,y_train)

Ridge(alpha=1)

In [ ]:
#模型评估
from sklearn.metrics import mean_squared_error
y_pred=estimator.predict(x_test)
print("MSE:",mean_squared_error(y_test,y_pred))

MSE: 20.384534023248012


In [ ]:
estimator.intercept_

array([-391.95797255])

In [ ]:
estimator.coef_

array([ 1.95479899e+03,  1.24812296e+02, -3.05111692e+02, -7.01192625e+02,
        4.99464443e+02, -7.62551801e+02, -3.76672087e+02,  4.35738454e+02,
       -8.37249018e+02,  5.39044400e+02, -9.42438614e-01,  8.23127043e+02,
       -1.32443091e+03])

In [ ]:
y_pred

array([-4.09310207e+03, -1.24789891e+03,  1.36780268e+04, -2.84396875e+03,
        1.24153281e+03,  4.91179282e+02, -4.80312422e+03, -2.98151972e+03,
       -1.17809867e+03,  8.76253743e+02, -4.46959177e+02, -3.92333075e+03,
        6.54078856e+01, -1.35074242e+03,  1.17472599e+03, -2.65271114e+03,
       -6.94716702e+02, -1.48710235e+03, -1.26962892e+03,  9.63837186e+01,
        4.20675550e+02,  2.36338568e+03,  1.01500889e+03,  7.54552987e+02,
        6.12663329e+02, -1.95075638e+03, -4.50342816e+02, -2.52439556e+01,
        1.15861466e+01, -1.99577985e+03,  7.72822499e+01, -5.17337621e+02,
       -2.21468745e+03,  5.59104144e+02, -2.79338901e+03, -4.29322654e+02,
        1.56822058e+02,  4.62680801e+02, -3.99169891e+02,  8.79357496e+02,
       -2.65223258e+03,  1.29665848e+03, -2.97044309e+02,  3.11766472e+03,
        2.09713217e+04,  2.78627740e+02, -1.21634920e+03, -1.09107846e+03,
       -1.23901173e+03,  5.48423516e+01, -1.52467665e+03, -8.40667613e+01,
        5.27338190e+02, -